# Generated by Django 3.2.4 on 2021-11-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_com',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_description',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
